version: '3'
services:
  app:
    build: .
    command:
      ['./wait_for_it.sh', 'mysql:3306', '--', 'pm2-runtime', './app/index.js']
    ports:
      - '8888:8888'
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - ./node_modules:/home/nodejs/node_modules
      - ./app/public:/home/nodejs/app/public

  mysql:
    build:
      context: ./config/mysql
      args:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - '3306'

  nginx:
    image: nginx:1.15
    depends_on:
      - app
    links:
      - app
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
