# create a new Pizza
mutation newPizza {
  newPizza(input: { size: { inches: 12 }, toppings: [{ name: "pepperoni" }] }) {
    id
    toppings {
      name
      price
    }
    size {
      inches
      price
    }
  }
}

mutation newOrder {
  newOrder(input: { pizzas: [{ id: 8 }], total: 30 }) {
    id
    pizzas {
      id
    }
    total
  }
}

mutation login {
  login(email: "test@michaelhueter.com", password: "1234") {
    token
  }
}
