type User {
  id: ID!
  firstName: String!
  lastName: String!
  email: String!
  orders: [Order]
}

input NewUserInput {
  firstName: String!
  lastName: String!
  email: String!
  password: String!
}

type Token {
  token: String!
}

extend type Query {
  users: [User]!
  user(id: ID!): User
  myProfile: User!
}

extend type Mutation {
  removeUser(id: ID!): User!
  signup(input: NewUserInput!): Token!
  login(email: String!, password: String!): Token!
}
