type Order {
  id: ID!
  userId: ID!
  total: Float!
  createdAt: Date!
  pizzas: [Pizza]
}

input NewOrderInput {
  userId: ID!
  pizzas: [NewPizzaInput]!
  total: Float!
}

extend type Query {
  orders: [Order]!
  order(id: ID!): Order
}

extend type Mutation {
  newOrder(input: NewOrderInput!): Order!
}
